apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: my-note-app
spec:
  selector:
    matchLabels:
      app: my-note-app
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: my-note-app
    spec:
      containers:
        - name: my-note-app
          image: abhijit28/my-note-app:latest # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000 # The port that the container is running on in the cluster